/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package au.com.tyo.antelope.jni;

public interface AntelopeConstants {
  public final static int FILENAME_INDEX = AntelopeJNI.FILENAME_INDEX_get();
  public final static int NULL = AntelopeJNI.NULL_get();
  public final static int ANT_ERROR_UNKNOWN = AntelopeJNI.ANT_ERROR_UNKNOWN_get();
  public final static int ANT_ERROR_NONE = AntelopeJNI.ANT_ERROR_NONE_get();
  public final static int ANT_ERROR_SIGNATURE_MISMATCH = AntelopeJNI.ANT_ERROR_SIGNATURE_MISMATCH_get();
  public final static int ANT_ERROR_VERSION_MISMATH = AntelopeJNI.ANT_ERROR_VERSION_MISMATH_get();
  public final static int ANT_ERROR_FILE_TYPE_MISMATCH = AntelopeJNI.ANT_ERROR_FILE_TYPE_MISMATCH_get();
  public final static int ANT_ERROR_INDEX_READING = AntelopeJNI.ANT_ERROR_INDEX_READING_get();

}
