/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package au.com.tyo.antelope.jni;

public class AntelopeJNI {
  public final static native int NULL_get();
  public final static native long new_ATIRE_API_remote();
  public final static native void delete_ATIRE_API_remote(long jarg1);
  public final static native int ATIRE_API_remote_open(long jarg1, ATIRE_API_remote jarg1_, String jarg2);
  public final static native int ATIRE_API_remote_close(long jarg1, ATIRE_API_remote jarg1_);
  public final static native String ATIRE_API_remote_get_connect_string(long jarg1, ATIRE_API_remote jarg1_);
  public final static native int ATIRE_API_remote_load_index(long jarg1, ATIRE_API_remote jarg1_, String jarg2, String jarg3);
  public final static native String ATIRE_API_remote_describe_index(long jarg1, ATIRE_API_remote jarg1_);
  public final static native String ATIRE_API_remote_search__SWIG_0(long jarg1, ATIRE_API_remote jarg1_, String jarg2, long jarg3, long jarg4, String jarg5);
  public final static native String ATIRE_API_remote_search__SWIG_1(long jarg1, ATIRE_API_remote jarg1_, String jarg2, long jarg3, long jarg4);
  public final static native String ATIRE_API_remote_get_document(long jarg1, ATIRE_API_remote jarg1_, long jarg2, long jarg3);
  public final static native String ATIRE_API_remote_send_command(long jarg1, ATIRE_API_remote jarg1_, String jarg2);
  public final static native void ATIRE_API_remote_exit(long jarg1, ATIRE_API_remote jarg1_);
  public final static native int ATIRE_API_server_CHANNEL_FILE_get();
  public final static native int ATIRE_API_server_CHANNEL_SOCKET_get();
  public final static native int ATIRE_API_server_CHANNEL_MEMORY_get();
  public final static native int ATIRE_API_server_XML_get();
  public final static native int ATIRE_API_server_JSON_get();
  public final static native long new_ATIRE_API_server();
  public final static native void delete_ATIRE_API_server(long jarg1);
  public final static native void ATIRE_API_server_initialize(long jarg1, ATIRE_API_server jarg1_);
  public final static native long ATIRE_API_server_get_atire(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_set_params__SWIG_0(long jarg1, ATIRE_API_server jarg1_, int jarg2, long jarg3);
  public final static native void ATIRE_API_server_set_params__SWIG_1(long jarg1, ATIRE_API_server jarg1_, String jarg2);
  public final static native void ATIRE_API_server_set_ant_version(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native void ATIRE_API_server_start(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_loop(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_poll(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_poll_and_process(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_process_command(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_interrupt(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_finish(long jarg1, ATIRE_API_server jarg1_);
  public final static native int ATIRE_API_server_run__SWIG_0(long jarg1, ATIRE_API_server jarg1_);
  public final static native int ATIRE_API_server_run__SWIG_1(long jarg1, ATIRE_API_server jarg1_, String jarg2);
  public final static native void ATIRE_API_server_ant(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_start_stats(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_end_stats(long jarg1, ATIRE_API_server jarg1_);
  public final static native long ATIRE_API_server_get_stats(long jarg1, ATIRE_API_server jarg1_);
  public final static native long ATIRE_API_server_get_search_time(long jarg1, ATIRE_API_server jarg1_);
  public final static native String ATIRE_API_server_version(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_prompt(long jarg1, ATIRE_API_server jarg1_);
  public final static native int ATIRE_API_server_is_interrupted(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_set_interrupted(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native int ATIRE_API_server_has_new_command(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_insert_command(long jarg1, ATIRE_API_server jarg1_, String jarg2);
  public final static native void ATIRE_API_server_set_outchannel(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native String ATIRE_API_server_get_outchannel_content(long jarg1, ATIRE_API_server jarg1_);
  public final static native int ATIRE_API_server_search__SWIG_0(long jarg1, ATIRE_API_server jarg1_, String jarg2);
  public final static native int ATIRE_API_server_search__SWIG_1(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_goto_result(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native String ATIRE_API_server_result_to_json(long jarg1, ATIRE_API_server jarg1_);
  public final static native long ATIRE_API_server_get_result(long jarg1, ATIRE_API_server jarg1_);
  public final static native int ATIRE_API_server_next_result(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_result_to_outchannel__SWIG_0(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native void ATIRE_API_server_result_to_outchannel__SWIG_1(long jarg1, ATIRE_API_server jarg1_);
  public final static native String ATIRE_API_server_load_document(long jarg1, ATIRE_API_server jarg1_);
  public final static native String ATIRE_API_server_get_document(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native String ATIRE_API_server_get_current_document(long jarg1, ATIRE_API_server jarg1_);
  public final static native void ATIRE_API_server_set_output_format(long jarg1, ATIRE_API_server jarg1_, int jarg2);
  public final static native void ATIRE_API_result_EMPTY_STRING_set(String jarg1);
  public final static native String ATIRE_API_result_EMPTY_STRING_get();
  public final static native int ATIRE_API_result_MAX_TITLE_LENGTH_get();
  public final static native void ATIRE_API_result_rank_set(long jarg1, ATIRE_API_result jarg1_, int jarg2);
  public final static native int ATIRE_API_result_rank_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_docid_set(long jarg1, ATIRE_API_result jarg1_, int jarg2);
  public final static native int ATIRE_API_result_docid_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_rsv_set(long jarg1, ATIRE_API_result jarg1_, float jarg2);
  public final static native float ATIRE_API_result_rsv_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_title_set(long jarg1, ATIRE_API_result jarg1_, String jarg2);
  public final static native String ATIRE_API_result_title_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_snippet_set(long jarg1, ATIRE_API_result jarg1_, String jarg2);
  public final static native String ATIRE_API_result_snippet_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_document_name_set(long jarg1, ATIRE_API_result jarg1_, String jarg2);
  public final static native String ATIRE_API_result_document_name_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native void ATIRE_API_result_answer_list_set(long jarg1, ATIRE_API_result jarg1_, long jarg2);
  public final static native long ATIRE_API_result_answer_list_get(long jarg1, ATIRE_API_result jarg1_);
  public final static native long new_ATIRE_API_result();
  public final static native void delete_ATIRE_API_result(long jarg1);
  public final static native void ATIRE_indexer_EMPTY_DOCUMENT_CONTENT_set(String jarg1);
  public final static native String ATIRE_indexer_EMPTY_DOCUMENT_CONTENT_get();
  public final static native void ATIRE_indexer_EMPTY_DOCUMENT_FILENAME_set(String jarg1);
  public final static native String ATIRE_indexer_EMPTY_DOCUMENT_FILENAME_get();
  public final static native int ATIRE_indexer_EMPTY_DOUCMENT_LENGTH_get();
  public final static native long new_ATIRE_indexer();
  public final static native void delete_ATIRE_indexer(long jarg1);
  public final static native void ATIRE_indexer_init__SWIG_0(long jarg1, ATIRE_indexer jarg1_, String jarg2);
  public final static native void ATIRE_indexer_init__SWIG_1(long jarg1, ATIRE_indexer jarg1_, int jarg2, long jarg3);
  public final static native void ATIRE_indexer_init__SWIG_2(long jarg1, ATIRE_indexer jarg1_, long jarg2);
  public final static native int ATIRE_indexer_finish(long jarg1, ATIRE_indexer jarg1_);
  public final static native long ATIRE_indexer_index_document__SWIG_0(long jarg1, ATIRE_indexer jarg1_, long jarg2, String jarg3);
  public final static native long ATIRE_indexer_index_document__SWIG_1(long jarg1, ATIRE_indexer jarg1_, long jarg2);
  public final static native void ATIRE_indexer_index_document__SWIG_2(long jarg1, ATIRE_indexer jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void ATIRE_indexer_index_document__SWIG_3(long jarg1, ATIRE_indexer jarg1_, String jarg2, String jarg3);
  public final static native long ATIRE_indexer_get_index(long jarg1, ATIRE_indexer jarg1_);
  public final static native long ATIRE_indexer_get_compression_text_factory(long jarg1, ATIRE_indexer jarg1_);
  public final static native long ATIRE_indexer_get_document_indexer(long jarg1, ATIRE_indexer jarg1_);
  public final static native boolean ATIRE_indexer_initialize();
}
