/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package au.com.tyo.antelope.jni;

public class ATIRE_API_remote {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ATIRE_API_remote(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ATIRE_API_remote obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AntelopeJNI.delete_ATIRE_API_remote(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ATIRE_API_remote() {
    this(AntelopeJNI.new_ATIRE_API_remote(), true);
  }

  public int open(String connect_string) {
    return AntelopeJNI.ATIRE_API_remote_open(swigCPtr, this, connect_string);
  }

  public int close() {
    return AntelopeJNI.ATIRE_API_remote_close(swigCPtr, this);
  }

  public String get_connect_string() {
    return AntelopeJNI.ATIRE_API_remote_get_connect_string(swigCPtr, this);
  }

  public int load_index(String doclist_filename, String index_filename) {
    return AntelopeJNI.ATIRE_API_remote_load_index(swigCPtr, this, doclist_filename, index_filename);
  }

  public String describe_index() {
    return AntelopeJNI.ATIRE_API_remote_describe_index(swigCPtr, this);
  }

  public String search(String query, long top_of_page, long page_length, String ranker) {
    return AntelopeJNI.ATIRE_API_remote_search__SWIG_0(swigCPtr, this, query, top_of_page, page_length, ranker);
  }

  public String search(String query, long top_of_page, long page_length) {
    return AntelopeJNI.ATIRE_API_remote_search__SWIG_1(swigCPtr, this, query, top_of_page, page_length);
  }

  public String get_document(long docid, SWIGTYPE_p_long_long length) {
    return AntelopeJNI.ATIRE_API_remote_get_document(swigCPtr, this, docid, SWIGTYPE_p_long_long.getCPtr(length));
  }

  public String send_command(String command) {
    return AntelopeJNI.ATIRE_API_remote_send_command(swigCPtr, this, command);
  }

  public void exit() {
    AntelopeJNI.ATIRE_API_remote_exit(swigCPtr, this);
  }

}
