/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package au.com.tyo.antelope.jni;

public class SWIGTYPE_p_ANT_index_document {
  private transient long swigCPtr;

  protected SWIGTYPE_p_ANT_index_document(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ANT_index_document() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_ANT_index_document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

